In [1]:
import tensorflow as tf

In [3]:
#2021F-BSE-180 , section:C

import tensorflow as tf

ts = tf.constant([100, 200, 300], dtype=tf.float32)
sc = 3.0
result_tensor = ts * sc

print("Original Tensor:", ts.numpy())
print("Scalar Value:", sc)
print("Result Tensor (After multiplying the tensor by the scalar):", result_tensor.numpy())

Original Tensor: [100. 200. 300.]
Scalar Value: 3.0
Result Tensor (After multiplying the tensor by the scalar): [300. 600. 900.]


In [6]:
import tensorflow as tf

vector1 = tf.constant([1, 3, 5], dtype=tf.float32)
vector2 = tf.constant([2, 4, 6], dtype=tf.float32)
dot_product = tf.reduce_sum(tf.multiply(vector1, vector2))

print("Vector 1:", vector1.numpy())
print("Vector 2:", vector2.numpy())
print("Dot product of the two vectors:", dot_product.numpy())

Vector 1: [1. 3. 5.]
Vector 2: [2. 4. 6.]
Dot product of the two vectors: 44.0


In [11]:



import tensorflow as tf

matrix1 = tf.constant([[1, 2],  [3, 4]])
matrix2 = tf.constant([[5, 6],  [7, 8]])
addition_result = matrix1 + matrix2
subtraction_result = matrix1 - matrix2
matrix_multiplication_result = tf.matmul(matrix1, matrix2)

print("Matrix 1:")
print(matrix1.numpy())
print("\nMatrix 2:")
print(matrix2.numpy())
print("\nAddition Result:")
print(addition_result.numpy())
print("\nSubtraction Result:")
print(subtraction_result.numpy())
print("\nMatrix Multiplication Result:")
print(matrix_multiplication_result.numpy())


Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Addition Result:
[[ 6  8]
 [10 12]]

Subtraction Result:
[[-4 -4]
 [-4 -4]]

Elementwise Multiplication Result:
[[ 5 12]
 [21 32]]

Matrix Multiplication Result:
[[19 22]
 [43 50]]
